### PR TITLE
Browserify branch updates

### PR DESCRIPTION
**Pull request by bluespore**
- Fix `undef` unused variable error in Travis test
- Bump version

### CODE REVIEW

**Comment by bluespore** [comment]
@amsul Looks like there's a bit of work outside of the updates I've made here to get it working with the tests.

Regardless, these changes were required for me to use this repo with Browserify, so I can `require('pickadate')`. 

Based on the comments by @mogarick https://github.com/amsul/pickadate.js/issues/365

I'm currently using my own fork, but it'd be great to get this repo updated, it's an awesome plugin so thanks for the work you've put in so far.

**Comment by tsm91** [comment]
:+1:

**Comment by rattrayalex** [comment]
Why hasn't this been merged?

**Comment by tsm91** [comment]
@rattrayalex good question

**Comment by rattrayalex** [comment]
Does it need to be rebased or something? Would be happy to help if possible...

**Comment by DanielRuf** [comment]
At least there are failing unit tests.

Also I guess this is obsolete now as there is already [this](https://github.com/amsul/pickadate.js/blob/master/lib/picker.js#L8-L21)

**Comment by DanielRuf** [comment]
Can we close this?

**Comment by DanielRuf** [comment]
Closing for now.

**Pull request closed without merging**
