### PR TITLE
Added missing translate for Hungarian language

### PR DESCRIPTION
**Pull request by gergo85**

### CODE REVIEW

**Comment by bl4ckdu5t** [comment]
Already merged #811 which is similar with more

**Comment by amsul** [comment]
@bl4ckdu5t this actually has more 😉

**Comment by amsul** [comment]
@gergo85 or @bl4ckdu5t can you please resolve the conflicts?

**Comment by gergo85** [comment]
The [ 'V', 'H', 'K', 'Sze', 'CS', 'P', 'Szo' ] is a correct typography instead of [ 'V', 'H', 'K', 'SZe', 'CS', 'P', 'SZo' ].

**Pull request merged**
