### PR TITLE
suppress outline on the root picker element

### PR DESCRIPTION
**Pull request by DanielRuf**
See https://github.com/Dogfalo/materialize/issues/4793

### CODE REVIEW

**Comment by tomscholz** [comment]
Maybe you could try to make the PR against the next branch

**Comment by DanielRuf** [comment]
@tomscholz does this make any difference? Because the current contributing file says that we should file PRs against the master branch and both branches have almost the same date when they were last updated.

See https://github.com/amsul/pickadate.js/blob/master/CONTRIBUTING.md

**Comment by tomscholz** [comment]
Did not see that. Sorry. Yes, I guess then it would make no difference

**Comment by DanielRuf** [comment]
Bump.

**Comment by DanielRuf** [comment]
@tomscholz do you think we should keep it there for keyboard users / a11y?

Or should this be done with what-input and other solutions?

**Comment by tomscholz** [comment]
Sorry for the delay :) I think this solution is great 👍

**Comment by DanielRuf** [comment]
> Sorry for the delay :) I think this solution is great 👍

Thanks. For other solutions I suggest using https://github.com/ten1seven/what-input to apply the needed focus styles globally.

**Pull request merged**
