### PR TITLE
Delete fa_ir.js to fix bower error

### PR DESCRIPTION
**Pull request by calvinlough**
Fix for the following error:

```
Merge error: conflicting capitalizations:
pickadate/lib/translations/fa_IR.js in /tmp/funnel-dest_33herW.tmp
pickadate/lib/translations/fa_ir.js in /tmp/funnel-dest_33herW.tmp
Remove one of the files and re-add it with matching capitalization.
We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux.
```

### CODE REVIEW

**Comment by mfpiccolo** [comment]
We are running into this also with ember-cli deploying to heroku.  We are going back to 3.5.5 for the moment until this is resolved.

**Comment by campbecf** [comment]
This should fix #685

**Comment by olivierlesnicki** [comment]
Any updates? Also running into this...

**Comment by amsul** [comment]
Oh wow, that’s not nice. Thanks for the fix @calvinlough!

**Comment by calvinlough** [comment]
@amsul No probs! You work at PumpUp don't you? As you can see from my out-of-date profile picture, I used to work there

**Comment by amsul** [comment]
@calvinlough I noticed from your name! Heard quite a bit about you :). Hope you’re killing it over at FreshBooks :+1:

**Comment by sly7-7** [comment]
Is this fix going to be merged ? Otherwise, is there any workaround ?

**Comment by olivierlesnicki** [comment]
cc @amsul

**Comment by renaudleo** [comment]
:)

**Pull request merged**
