### PR TITLE
Add boolean `closeOnSelect` and `closeOnClear` options

### LINKED ISSUE #596: Add boolean `closeOnSelect` option
I'm customizing the Pickadate picker a bit, and would like to prevent the picker from closing when a date is selected. Unfortunately, there's no simple way I can see to do that right now outside of modifying the source. :/

To solve this, I'd like to add a boolean option `closeOnSelect` (defaulting to true) that determines whether to close the picker after a value is selected. I can write the code, but I thought I'd check if you'd be open to merging it before I spend the time writing it.

Let me know!

Thanks.

### PR DESCRIPTION
**Pull request by vergenzt**
Closes #596.

### CODE REVIEW

**Comment by amsul** [comment]
Sweet! I'll merge this in for v3.5.5

Thanks :)

**Comment by amsul** [comment]
Hey @vergenzt, can you please bring this upstream to the latest `master`? I'd like to merge this in asap.

The demos and docs have been moved to `gh-pages` as a jekyll site and just the library code lives in `master` now.

Thanks!

**Comment by vergenzt** [comment]
Will do!

**Comment by vergenzt** [comment]
@amsul I assume I should submit a separate pull request for the `gh-pages` branch?

**Comment by vergenzt** [comment]
Also oops. Forgot to run the build before pushing!

**Comment by vergenzt** [comment]
@amsul When I run `grunt build --verbose` I get a warning that "`Warning: Task "document-once" not found. Use --force to continue.`" Any ideas? :/

**Comment by amsul** [comment]
@vergenzt ah, that task was removed. I just commit the fix to the Gruntfile. Can you please try that again?

And yes, the docs changes should go in the `gh-pages` branch now :)

**Comment by vergenzt** [comment]
Sorry this is taking so long, I'm just getting confused about what's expected. -_-

Should I commit and add the compiled and minified results of `grunt build --verbose` to the PR? It changes some translations in addition to the themes and `js` files.

**Comment by vergenzt** [comment]
Ping?

**Comment by amsul** [comment]
As long as `grunt test` passes, you should be good here :)

I'll merge this in over the weekend. Thanks!!

**Comment by amsul** [comment]
Looking at the changed files now.. can you please also add tests for these two cases?

Right after this test would be perfect: `Base keyboard events - Set and clear`

**Comment by vergenzt** [comment]
Yes! I'm sorry, I thought I had done that.

Really sorry about the latency on this. I started classes a few weeks ago and have been swamped.

**Comment by amsul** [comment]
I wasn't able to merge the commit automatically so I did a manual merge.

Thanks for the contribution!

**Pull request closed without merging**
