### PR TITLE
Prevent Chrome 62 autofill from closing the picker

### LINKED ISSUE #1032: Changing month closes date picker on Chrome Version 62.0.3202.89
I downloaded the latest version of Chrome, version 62.0.3202.89, and using this breaks our date picker.

When I attempt to change months by selecting the previous month or next month arrow, the date picker closes.

My colleague has just pointed out that this issue is not present on the website: http://amsul.ca/pickadate.js/date/ on the latest version of Chrome, so it may be an issue with our system and I will verify. Thanks folks.

Update 1: Seeing an issue here: https://github.com/amsul/pickadate.js/blob/master/lib/picker.js#L266.

This section of code is only triggered in the latest version of Chrome.

Update 2: `target` is returning the incorrect value on line https://github.com/amsul/pickadate.js/blob/master/lib/picker.js#L268 in Chrome but I am not sure why? I think again that this could be an issue with our system.

Update 3: Using `var target = event.currentTarget` instead of `var target = event.target` seems to work on the same line mentioned above. However, the date picker will not close unless a date is selected.

Update 4: I have a input field on the same screen as the datepicker that is of type password with autocomplete off. I think this is the issue. If I remove this field or change it to disabled there is no issue with the date picker.

Update 5: We believe there is an issue with autocomplete in Chrome, we have a password input field on the same screen that uses `autocomplete="off"` but we think we should be using [`autocomplete="new-password"`](https://stackoverflow.com/a/43784451/1945948) and that this was somehow interfering with the date picker in Chrome. I will confirm this.

Final update: So autocomplete will cause an issue with Chrome in the latest version, possibly since earlier this year, if you also have a password input field on the same view with autocomplete="off".

### PR DESCRIPTION
**Pull request by sigginet**
Closes #1032
Thanks go to @Mwni for finding a solution

### CODE REVIEW

**Comment by nicolasrouanne** [comment]
Hey, thanks all. Can you merge it and update the `gem` if it's working? Because the `autocomplete="new-password"` I have is just hell 💀 😆

**Comment by wimvdc** [comment]
Works like a charm, thanks!

**Comment by nicolasrouanne** [comment]
Ping 😄

**Comment by DanielRuf** [comment]
Please provide a codepen that demonstrates the issue that is solved with this PR.

**Pull request merged**
