### PR TITLE
Can set all day of the week on the first day

### LINKED ISSUE #894: Set firstDay as wednesday
Hi, im trying to change the firstDay of the week to wednesday. I'm looking onto the calendar.settings.firstDay parameter and trying to override the existing array of days but with no success.

Hope you can give me some tips about it, thanks ^^

### PR DESCRIPTION
**Pull request by tanihiro**
Fixes #894 

The current can set 0(Sunday) or 1(Monday) to first day options. But I want set 2(Tuesday).
So it was modified that it can be set to 0 to 6 options of first day.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Why should be Tuesday the first day of the week?

**Comment by DanielRuf** [comment]
Please describe some actual use cases dor this change.

**Comment by Takazudo** [comment]
In the project I'm working on, the system needed to define Tuesday as the first of the week. In the system, machines that are organized by the system treat Tuesday as the first of the week. So I needed that feature.

**Comment by DanielRuf** [comment]
This makes no sense to add it to the internal code as we have just 3 different variants in the world:
http://chartsbin.com/view/41671
Saturday, Sunday, Monday

**Comment by DanielRuf** [comment]
This would also break the current behavior.

**Comment by amsul** [comment]
Not a problem in v5 :)

Closing this as most people don't need to set it to Tuesday

**Pull request closed without merging**
