### PR TITLE
Add this.blur() to stop flash of keyboard on iOS

### LINKED ISSUE #1133: iOS Keyboard
When you click in the date field, as the date picker is opening the iOS keyboard appears and then disappears on the bottom of the screen, this plays havoc with body scroll lock.

### PR DESCRIPTION
**Pull request by MatthewKennedy**
Add this.blur() to stop flash of keyboard on iOS

Fixes #1133

### CODE REVIEW

**Comment by amsul** [comment]
@MatthewKennedy the `readOnly` attribute should already be preventing this as mentioned here: https://amsul.ca/pickadate.js/date/#editable

**Comment by MatthewKennedy** [comment]
Hi @amsul 

I had to make a video showing the issue, let me know what you think?
https://www.youtube.com/watch?v=HHXp3-cigho&feature=youtu.be

**Comment by amsul** [comment]
@MatthewKennedy video not available anymore?

**Comment by MatthewKennedy** [comment]
@amsul try now

**Comment by amsul** [comment]
Ah yknow what..I just checked to confirm and it seems like this is a regression in one of the newer versions of iOS. It was specifically solved in the past by adding the `readonly` attribute.

But, the problem with this solution is that it breaks the tabindex flow when using the picker on a laptop/desktop. We'll need to find a way to do this without affecting the other use cases 🤔

**Pull request closed without merging**
