### PR TITLE
fixed editable true functionality

### PR DESCRIPTION
**Pull request by PiotrObrebski**
This simple change will make "editable: true" work properly.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi @PiotrObrebski,

Unfortunately this breaks many things. Please see the failing CI build.

**Comment by DanielRuf** [comment]
Which issue does this resolve?
Also please provide a codepen to demonstrate the failing and the fixed case.

https://github.com/amsul/pickadate.js/search?q=editable&type=Issues

**Comment by PiotrObrebski** [comment]
Hi @DanielRuf,
in my project, someone made a mistake initializing your picker.js. Sorry for taking your time. This commit solves only my case.

**Comment by PiotrObrebski** [comment]
Hi @DanielRuf,
In my project, someone made a mistake initializing your picker.js. Sorry for taking your time. This commit solves only my case.

**Comment by DanielRuf** [comment]
No problem. I'm glad that you could resolve it.

**Pull request closed without merging**
