### PR TITLE
fixed bugs and added a today function

### PR DESCRIPTION
**Pull request by elieobeid7**
bug fixes: 
Removed "s" from "autofocus" and "u"  "date-value"
Removed two obsolete input forms

Added a function to return current date

### CODE REVIEW

**Comment by DanielRuf** [comment]
So far so good but why were the date formats changed?

**Comment by DanielRuf** [comment]
Not yet sure if the failing tests are related.

**Comment by elieobeid7** [comment]
Honestly I forgot what the issue is about, it's been more than two years :)

**Comment by DanielRuf** [comment]
Can you rebase the PR on the current head of master?

**Comment by elieobeid7** [comment]
will do that next weekend probably

**Comment by DanielRuf** [comment]
> will do that next weekend probably

Friendly bump =)

**Comment by DanielRuf** [comment]
> yeah will do it tomorrow promise i'll put it as a reminder, im at work now, cant

No problem and no hurry, just wanted to remind you that you have a PR open =)

**Comment by elieobeid7** [comment]
What I don't understand is that all I did is editing a test file, which I don't remember a thing about since it was 2015, but anyhow if all I did is adding a test which is breaking the build then why not just delete the test and close the issue?

I mean isn't just a test? I don't see any changes in lib folder, so I broke a test and didn't contribute to the core library. Anyhow I'll rebase

**Comment by elieobeid7** [comment]
I closed the issue and deleted the pull request, I don't see any value in the code I've written

**Comment by elieobeid7** [comment]
it was failing because in the newer version, you're pulling jquery from the node_modules and you're not shipping it with the repo.

**Comment by DanielRuf** [comment]
jQuery should be never shipped with a library =)

**Comment by DanielRuf** [comment]
And still: a rebase or pushing an empty commit to trigger a new build would have fixed it.

https://travis-ci.org/amsul/pickadate.js/builds/87535668

This is just related to the previous setup.

**Comment by DanielRuf** [comment]
Still, your PR is good. Would like to see it reopened and a new build trggered =)

**Comment by DanielRuf** [comment]
`git commit --allow-empty -m "chore: trigger new build"`

**Pull request closed without merging**
