### PR TITLE
Make sure $.fn.pickadate and $.fn.pickatime have been defined before set up translations

### LINKED ISSUE #742: Check whether $.fn.pickadate and $.fn.pickatime have been defined before set up translations
When I only include picker.js, picker.date.js, and translations/zh_CN.js, it produces an error: `TypeError: jQuery.fn.pickatime is undefined`.

It's better to check whether $.fn.pickadate and $.fn.pickatime have been defined before using them.
```
if (jQuery.fn.pickadate){
    jQuery.extend( jQuery.fn.pickadate.defaults, {
    }
}

if (jQuery.fn.pickatime){
    jQuery.extend( jQuery.fn.pickatime.defaults, {
    }
}
```
Or, we could set a default value to make sure they exists.
```
jQuery.fn.pickadate = jQuery.fn.pickadate || {};
jQuery.fn.pickatime = jQuery.fn.pickatime || {};
```

### PR DESCRIPTION
**Pull request by bianjp**
Fix #742

### CODE REVIEW

**Comment by daminufe** [comment]
@amsul could you please merge it? It's quite annoying to have always the `Uncaught TypeError: Cannot read property 'defaults' of undefined` error. :smiley:

**Comment by ddevaal** [comment]
:+1 please merge this.

**Comment by pionl** [comment]
merge would be great. Thank you

**Comment by janstieler** [comment]
:+1:

**Comment by cassln** [comment]
:+1: merge, please

**Comment by DanielRuf** [comment]
This PR has currently conflicts. The compressed files should not be changed or pushed.

I'll try to resolve the conflict.

**Comment by amsul** [comment]
Coming around to this finally 😅

Yeah this is a bit much..Simply changing the order of the imports would fix this problem as well.

Anyways, not a problem in v5 :)

**Pull request closed without merging**
