### PR TITLE
Fixed typo, created today function

### PR DESCRIPTION
**Pull request by elieobeid7**
- Added today function so that today works in datepicker
- Fixed Typos
- Removed unused input
- Added <html> </html> tags

### CODE REVIEW

**Comment by elieobeid7** [comment]
Sorry for the stupid question but it's been a while since the last time i did pull request on github

- Do you need anything else from me? I delete my fork? Will you merge the changes or is there things I need to do?

- Could you add `--verbose` to npm install in travis? `npm install --verbose`, so that when npm fails we'll know why, I didn't see `verbose` argument in the last travis build and I don't know how travis work, maybe I'm missing something

**Comment by DanielRuf** [comment]
Please do not delete your fork or branch until it is merged.

Your PR looks good so far :+1:

`--verbose` is not needed as the output and stacktraces should be already sufficient if something fails.

Also `--verbose` is not needed for CI and the builds would take longer.

**Comment by elieobeid7** [comment]
Okay, by the way the date picker won't work if I remove the `today` code that I've written. Maybe it's just me maybe not.

In any case, I think it's best to remove

```
var today = new Date();
var dd = today.getDate();
var mm = today.getMonth() + 1; //January is 0!
var yyyy = today.getFullYear();
if (dd < 10) {
	dd = '0' + dd;
}
if (mm < 10) {
	mm = '0' + mm;
}
today = dd + '/' + mm + '/' + yyyy;
```

From date.html and put it in `picker.date.js`

**Comment by DanielRuf** [comment]
Nit needed in my opinion as this is just logic for the unit tests and the related files. Testcode should not be in the core files of a library.

**Pull request merged**
