### PR TITLE
Fix issue #634

### PR DESCRIPTION
**Pull request by rollbrettler**

### CODE REVIEW

**Comment by snocorp** [comment]
I like this approach.

**Comment by gilbarbara** [comment]
:+1:

**Comment by mfkp** [comment]
:+1:

**Comment by tibineagu** [comment]
:+1:

**Comment by jermspeaks** [comment]
:+1:

**Comment by amsul** [comment]
The best solution for this is mentioned here: https://github.com/amsul/pickadate.js/issues/667#issuecomment-85983322

Closing this in favor of that. Cheers!

**Pull request closed without merging**
